version: '3.0'
services:
  elasticsearch:
    container_name: pooch-es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: always
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    - ELASTIC_PASSWORD=test
    - ELASTIC_USERNAME=pooch
    ports:
    - 9200:9200
    - 9300:9300
  kibana:
    container_name: pooch-kb-container
    image: docker.elastic.co/kibana/kibana:7.10.2
    restart: always
    environment:
    - ELASTICSEARCH_HOSTS=http://pooch-es-container:9200
    - ELASTICSEARCH_USERNAME=pooch
    - ELASTICSEARCH_PASSWORD=test
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601
networks:
  es-net:
    driver: bridge