package com.pooch.api.entity.notification.email.template;

public enum EmailTemplateUuid {

    WELCOME_GROOMER_EMAIL,
    WELCOME_PARENT_EMAIL,
    GROOMER_REQUEST_PASSWORD_RESET,
    PARENT_REQUEST_PASSWORD_RESET,
    GROOMER_NEW_BOOKING_EMAIL,
    PARENT_NEW_BOOKING_EMAIL,
    DEMO_CONFIRMATION_EMAIL,
    DEMO_INFO_EMAIL,
    GROOMER_WAITLIST,
    GROOMER_SUBSCRIBER
    ;
}
